name: Job Checker
description: Checks changes to decided which jobs are required to run
author: Rotki Solutions GmbH
inputs:
  token:
    description: Github token
    required: true
  colibri_paths:
    description: Paths of files or directories that will trigger the colibri tasks
    required: false
  backend_paths:
    description: Paths of files or directories that will trigger the backend tasks
    required: true
  frontend_paths:
    description: Paths of files or directories that will trigger the frontend tasks
    required: true
  documentation_paths:
    description: Paths of files or directories that will trigger the documentation build
    required: true

outputs:
  colibri_tasks:
    description: Backend tasks should run
  backend_tasks:
    description: Backend tasks should run
  frontend_tasks:
    description: Frontend tasks should run
  documentation_tasks:
    description: Documentation tasks should run
  e2e_tasks:
    description: E2E tasks should run
  test_environment:
    description: nft | nightly | ''

runs:
  using: node20
  main: dist/index.js
